apiVersion: v2
name: web-service
description: A Helm chart for deploying web services with deployment, service, and ingress
type: application
version: 0.3.0
appVersion: "1.0"

dependencies:
  - name: common
    version: "0.2.0"
    repository: "https://eikon-solutions.github.io/helm-charts"